id: PE87CF7DB
initial_creation_type: input
source_metadata:
  title: Lhodrak Namkha Gyaltsen
  language: de
  description: 'Texts by Lhodrak Namkha Gyaltsen (lho brag nam mkha'' rgyal mtshan,
    1326–1401), also known as Drupchen Lekyi Dorje (grub chen las kyi rdo rje), who
    was a teacher of Tsongkhapa Lobzang Drakpa:'
  volume:
    e41eb778e0564b1d941a1e208ff93758:
      title: Averting Obstacles through Sitātapatrā
      parent: Averting Obstacles
created_at: '2022-03-01T00:36:28.850604'
last_modified_at: '2022-03-01T00:36:28.850606'
